# Generated by Django 5.1.1 on 2024-09-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=80)),
                ("text", models.TextField()),
                ("is_enable", models.BooleanField(default=False)),
                ("publish_date", models.DateField()),
                ("create_date", models.DateTimeField()),
                ("update_date", models.DateTimeField()),
            ],
        ),
    ]
