# Generated by Django 5.1.1 on 2024-09-14 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0002_alter_post_create_date_alter_post_publish_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="publish_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
