# Generated by Django 5.1.1 on 2024-09-14 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0004_comment"),
    ]

    operations = [
        migrations.RenameField(
            model_name="comment",
            old_name="create_date",
            new_name="create_time",
        ),
        migrations.RenameField(
            model_name="comment",
            old_name="update_date",
            new_name="update_time",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="create_date",
            new_name="create_time",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="publish_date",
            new_name="publish_time",
        ),
        migrations.RenameField(
            model_name="post",
            old_name="update_date",
            new_name="update_time",
        ),
    ]
